// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apidixbcujmqhxicjqut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwaWRpeGJjdWptcWh4aWNqcXV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNjEyMjgsImV4cCI6MjA3MDczNzIyOH0.K-fiCGGx5E6YEXXrqwt7GY2-w2acEzRDDY0lELbxlQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});